apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kie-service
  namespace: receipt-understanding
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: kie-service
  namespaceSelector:
    matchNames:
      - receipt-understanding
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
